# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0134ed407e4eeca9bf55364653f42b768d4cf5361b329827527aed862742cd3397065ee6737349cdb2e54030a516297a6dba27aa683eebfc7250a8e8ec2f298b

test:
  secret_key_base: 5ff2412227b7c26d05301eb8e153f95df775f3763daa15a894fa288e61d52a264bd40445254b116bead6fbf503eb69fbd1f58ced47afae17d9839114866f4783

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
